version: '3'
services:
  web:
    build: .
    ports:
    - "8088:8080"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - tomcat
  
  tomcat:
    image: tomcat
volumes:
  logvolume01: {}